-- GitHub Pages + Supabase版 文字だけポケモン対戦
-- Supabase SQL Editorで一度だけ実行してください。

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  role text not null default 'player' check (role in ('player','developer')),
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.content (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('species','ability','item','move','enemy_team')),
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists content_kind_idx on public.content(kind);

alter table public.profiles enable row level security;
alter table public.content enable row level security;

-- ログイン中のユーザーは自分のプロフィールを読めます。
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select to authenticated using (id = auth.uid());

-- 対戦データはログインユーザーなら読めます。
drop policy if exists "content_select_authenticated" on public.content;
create policy "content_select_authenticated" on public.content
  for select to authenticated using (true);

-- 開発者判定用ヘルパー。
create or replace function public.is_developer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'developer' and enabled = true
  );
$$;

-- 開発者だけがデータを変更できます。
drop policy if exists "content_insert_developer" on public.content;
create policy "content_insert_developer" on public.content
  for insert to authenticated with check (public.is_developer());

drop policy if exists "content_update_developer" on public.content;
create policy "content_update_developer" on public.content
  for update to authenticated using (public.is_developer()) with check (public.is_developer());

drop policy if exists "content_delete_developer" on public.content;
create policy "content_delete_developer" on public.content
  for delete to authenticated using (public.is_developer());

-- 新規Authユーザー作成時にプロフィールを自動作成。
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, role, enabled)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    'player',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- 最初のアカウントを開発者にしたい場合、Supabase Authでアカウントを作成した後に実行：
-- update public.profiles set role='developer' where username='あなたのユーザー名';

-- ユーザー同士のオンライン対戦用（追加）
create table if not exists public.online_battles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete set null,
  host_team jsonb,
  guest_team jsonb,
  host_selected jsonb,
  guest_selected jsonb,
  host_action jsonb,
  guest_action jsonb,
  state jsonb,
  status text not null default 'waiting' check (status in ('waiting','selection','battle','finished')),
  turn integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists online_battles_code_idx on public.online_battles(code);
create index if not exists online_battles_host_idx on public.online_battles(host_id);
create index if not exists online_battles_guest_idx on public.online_battles(guest_id);
alter table public.online_battles enable row level security;
drop policy if exists "online_battles_select_participant" on public.online_battles;
create policy "online_battles_select_participant" on public.online_battles for select to authenticated
using (host_id=auth.uid() or guest_id=auth.uid() or (status='waiting' and guest_id is null));
drop policy if exists "online_battles_insert_host" on public.online_battles;
create policy "online_battles_insert_host" on public.online_battles for insert to authenticated with check (host_id=auth.uid());
drop policy if exists "online_battles_update_participant" on public.online_battles;
create policy "online_battles_update_participant" on public.online_battles for update to authenticated using (host_id=auth.uid() or guest_id=auth.uid() or (status='waiting' and guest_id is null)) with check (host_id=auth.uid() or guest_id=auth.uid());
